### ISSUE TITLE
Newsletter subscription

### ISSUE THREAD

**Issue by j-maas** [Y0hy0h/lindyhop-aachen#37]
We should add the possibility to subscribe to our newsletter. Perhaps we could even list old newsletter in a similar way to "This Week in Rust" (https://this-week-in-rust.org/).

**Comment by j-maas** [comment]
We should talk to the ones that currently manage the mailing list, to ensure that it will interface well and that they are ok with it. Also research data privacy issues.

**Comment by j-maas** [comment]
I'm actually not convinced that it adds value to show old newsletters, because all their information will be outdated.

**Comment by bytesnake** [comment]
The best way to implement is a email client which just login the lindyhop mail account and looks for sent newsletters. https://github.com/jonhoo/rust-imap

**Comment by bytesnake** [comment]
Yeah I'm not sure whether we should show all of the old ones, but it would add no additional value nor additional cost. The only benefit I can think of is that we can find pages of old events more quickly. And its a nice fill-in for the page and shows that we are active.

**Comment by j-maas** [comment]
> The only benefit I can think of is that we can find pages of old events more quickly.

Can you come up with a convincing use case? I don't see the problem and I suspect that there might be other solutions. ;)

**Comment by j-maas** [comment]
> The best way to implement is a email client which just login the lindyhop mail account and looks for sent newsletters. https://github.com/jonhoo/rust-imap

I don't follow. Do you want to send mails or read them?

**Comment by j-maas** [comment]
But in any case, an easier way to subscribing is a really great idea!

**Comment by bytesnake** [comment]
> > The only benefit I can think of is that we can find pages of old events more quickly.
> 
> Can you come up with a convincing use case? I don't see the problem and I suspect that there might be other solutions. ;)

For example if we have an old "Tanz in den Mai" event and we are looking for the facebook page of last year (probably because of the text) we could look into the previous newsletters.

**Comment by bytesnake** [comment]
> > The best way to implement is a email client which just login the lindyhop mail account and looks for sent newsletters. https://github.com/jonhoo/rust-imap
> 
> I don't follow. Do you want to send mails or read them?

No read them, otherwise we would need to copy every newsletter in the database, with the client we just read old newsletter from the mail server and store them in the cache.

**Comment by j-maas** [comment]
> > > The only benefit I can think of is that we can find pages of old events more quickly.
> > 
> > 
> > Can you come up with a convincing use case? I don't see the problem and I suspect that there might be other solutions. ;)
> 
> For example if we have an old "Tanz in den Mai" event and we are looking for the facebook page of last year (probably because of the text) we could look into the previous newsletters.

Why would we want to do that? I am looking for a problem that makes people want to look for old stuff. ;)

**Comment by j-maas** [comment]
Ok, maybe it's easier if we split this again. I will open two new issues, and close this one, to make it easier to understand. I think we're both on the same track for #38, so we can discuss #39 separately.
