### ISSUE TITLE
Make admin actions sticky

### ISSUE THREAD

**Issue by j-maas** [Y0hy0h/lindyhop-aachen#46]
Stick admin actions such as save and delete to the bottom of the screen, so that they are also visible when there is a long list of occurrences.

**Comment by Y0hy0h** [comment]
Closed in d0a9ec0171d6d15056caa1a0a5be4bf8dfaa9b02.

**Comment by j-maas** [comment]
Closed in 37d614f5be304f2cf46f38c9ecff87c14edd0ffd.
